#############################################################################
# Makefile for building: plasonic
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  PLASONIC.pro
# Template: app
# Command: /home/sjpark/hironic/prebuilt5-6/plasonic-release/qtrpi/qtrpi/raspi/qt5/bin/qmake -o Makefile PLASONIC.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
CXX           = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qtrpi/raspbian/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qtrpi/raspbian/sysroot -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -Iinclude -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtSerialPort -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I. -I=/opt/vc/include -I=/opt/vc/include/interface/vcos/pthreads -I=/opt/vc/include/interface/vmcs_host/linux -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++
QMAKE         = /home/sjpark/hironic/prebuilt5-6/plasonic-release/qtrpi/qtrpi/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = plasonic1.0.0
DISTDIR = /home/sjpark/hironic/prebuilt5-6/plasonic-application/.tmp/plasonic1.0.0
LINK          = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/lib/arm-linux-gnueabihf -mfloat-abi=hard --sysroot=/opt/qtrpi/raspbian/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib
LIBS          = $(SUBLIBS) -L=/opt/vc/lib -L/opt/qtrpi/raspi/qt5pi/lib -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5SerialPort -lQt5Core -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/opt/vc/lib -lGLESv2 -lpthread 
AR            = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/useriface.cpp \
		src/sender.cpp \
		src/receiver.cpp \
		src/swupdater.cpp \
		src/logger.cpp qrc_qml.cpp \
		moc_useriface.cpp \
		moc_sender.cpp \
		moc_receiver.cpp \
		moc_swupdater.cpp \
		moc_logger.cpp
OBJECTS       = main.o \
		useriface.o \
		sender.o \
		receiver.o \
		swupdater.o \
		logger.o \
		qrc_qml.o \
		moc_useriface.o \
		moc_sender.o \
		moc_receiver.o \
		moc_swupdater.o \
		moc_logger.o
DIST          = /opt/qtrpi/raspi/qt5/mkspecs/features/spec_pre.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/linux.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/sanitize.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qdevice.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/device_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qconfig.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_functions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/spec_post.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resolve_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_post.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/warn_on.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resources.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/moc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/thread.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/file_copies.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exceptions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/yacc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/lex.prf \
		PLASONIC.pro include/hspsprotocol.h \
		include/common.h \
		include/useriface.h \
		include/sender.h \
		include/receiver.h \
		include/swupdater.h \
		include/logger.h src/main.cpp \
		src/useriface.cpp \
		src/sender.cpp \
		src/receiver.cpp \
		src/swupdater.cpp \
		src/logger.cpp
QMAKE_TARGET  = plasonic
DESTDIR       = 
TARGET        = plasonic


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PLASONIC.pro /opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf /opt/qtrpi/raspi/qt5/mkspecs/features/spec_pre.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/linux.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/sanitize.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qdevice.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/device_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qconfig.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_functions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/spec_post.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resolve_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_post.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/warn_on.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resources.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/moc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/thread.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/file_copies.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exceptions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/yacc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/lex.prf \
		PLASONIC.pro \
		qml.qrc \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Quick.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Gui.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Qml.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Network.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5SerialPort.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Core.prl
	$(QMAKE) -o Makefile PLASONIC.pro
/opt/qtrpi/raspi/qt5/mkspecs/features/spec_pre.prf:
/opt/qtrpi/raspi/qt5/mkspecs/common/unix.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/linux.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/sanitize.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/g++-base.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/g++-unix.conf:
/opt/qtrpi/raspi/qt5/mkspecs/qdevice.pri:
/opt/qtrpi/raspi/qt5/mkspecs/features/device_config.prf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
/opt/qtrpi/raspi/qt5/mkspecs/qconfig.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_labscontrols_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_labstemplates_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/features/qt_functions.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/qt_config.prf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf:
/opt/qtrpi/raspi/qt5/mkspecs/features/spec_post.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/exclusive_builds.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/default_pre.prf:
deployment.pri:
/opt/qtrpi/raspi/qt5/mkspecs/features/resolve_config.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/default_post.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/warn_on.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/qt.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/resources.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/moc.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/unix/opengl.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/unix/thread.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/file_copies.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/testcase_targets.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/exceptions.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/yacc.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/lex.prf:
PLASONIC.pro:
qml.qrc:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Quick.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Gui.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Qml.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Network.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5SerialPort.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PLASONIC.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents include/hspsprotocol.h include/common.h include/useriface.h include/sender.h include/receiver.h include/swupdater.h include/logger.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/useriface.cpp src/sender.cpp src/receiver.cpp src/swupdater.cpp src/logger.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		res/qml/Ultrasonic.qml \
		res/qml/AdminSettingTip.qml \
		res/qml/MainSettings.qml \
		res/qml/AdminSettingTime.qml \
		res/qml/Main.qml \
		res/qml/AdminEnterance.qml \
		res/qml/AdminSettings.qml \
		res/qml/AdminUpdateFw.qml \
		res/qml/Plasma.qml \
		res/images/admin_modebtn01_u.png \
		res/images/admin_numbtn06_d.png \
		res/images/main_standbybtn02_u.png \
		res/images/main_tip_timenum_red03.png \
		res/images/admin_backbtn_d.png \
		res/images/admin_timesetting_u.png \
		res/images/main_levelbar_00.png \
		res/images/main_tip_timenum_blue07.png \
		res/images/main_timenum_05.png \
		res/images/admin_modebtn01_d.png \
		res/images/main_standbybtn02_d.png \
		res/images/main_tip_timenum_red01.png \
		res/images/admin_numbtn02_u.png \
		res/images/admin_numbtn09_u.png \
		res/images/loading_bg01.png \
		res/images/admin_timesetting_d.png \
		res/images/main_tip_timenum_blue05.png \
		res/images/main_timenum_03.png \
		res/images/busyCircle.gif \
		res/images/loading_bg01.png \
		res/images/admin_numbtn02_d.png \
		res/images/admin_numbtn09_d.png \
		res/images/main_aniB02_shot.gif \
		res/images/main_tapbtn03_select.png \
		res/images/admin_OKbtn_u.png \
		res/images/main_tip_timenum_blue03.png \
		res/images/main_timenum_01.png \
		res/images/main_aniA01_standby_ready.png \
		res/images/admin_modebtn02_u.png \
		res/images/admin_OKbtn_d.png \
		res/images/main_tapbtn02_unselect.png \
		res/images/main_tip_timenum_bg02.png \
		res/images/admin_numbtn05_u.png \
		res/images/main_tip_timenum_blue01.png \
		res/images/admin_bg02.png \
		res/images/admin_modebtn02_d.png \
		res/images/loading_bar01.gif \
		res/images/main_levelnum_05.png \
		res/images/admin_numbtn05_d.png \
		res/images/logo_bi01.png \
		res/images/main_tapbtn05_unselect.png \
		res/images/admin_modebtn07_u.png \
		res/images/main_levelbtn01_u.png \
		res/images/main_tip_timenum_red08.png \
		res/images/main_levelnum_03.png \
		res/images/admin_modebtn05_u.png \
		res/images/main_levelbar_05.png \
		res/images/admin_numbtn01_u.png \
		res/images/message_caution_bg01.png \
		res/images/admin_numbtn08_u.png \
		res/images/main_aniA01_shot.gif \
		res/images/admin_modebtn07_d.png \
		res/images/main_tapbtn04_select.png \
		res/images/select_btn01_u.png \
		res/images/main_levelbtn01_d.png \
		res/images/main_levelnum_01.png \
		res/images/admin_modebtn05_d.png \
		res/images/main_tip_timenum_red06.png \
		res/images/main_aniB01_standby_ready.png \
		res/images/main_levelbar_03.png \
		res/images/admin_numbtn01_d.png \
		res/images/admin_numbtn08_d.png \
		res/images/main_timenum_08.png \
		res/images/main_soundbtn02_u.png \
		res/images/main_bg_01.png \
		res/images/select_btn01_d.png \
		res/images/main_levelbtn02_u.png \
		res/images/main_tip_timenum_red04.png \
		res/images/main_standbybtn01_u.png \
		res/images/admin_cancelbtn_u.png \
		res/images/main_levelbar_01.png \
		res/images/main_tip_timenum_blue08.png \
		res/images/main_timenum_06.png \
		res/images/admin_numbtn04_u.png \
		res/images/main_soundbtn02_d.png \
		res/images/main_bg_02.png \
		res/images/main_levelbtn02_d.png \
		res/images/main_standbybtn01_d.png \
		res/images/main_soundbtn01_u.png \
		res/images/admin_cancelbtn_d.png \
		res/images/main_tip_timenum_red02.png \
		res/images/main_tip_timenum_blue06.png \
		res/images/admin_numbtn04_d.png \
		res/images/main_timenum_04.png \
		res/images/main_tapbtn03_unselect.png \
		res/images/admin_timesetting_numbox.png \
		res/images/main_soundbtn01_d.png \
		res/images/main_tip_timenum_red00.png \
		res/images/admin_tipsetting_u.png \
		res/images/main_tapbtn01_select.png \
		res/images/main_tip_timenum_blue04.png \
		res/images/select_btn02_u.png \
		res/images/admin_modebtn04_u.png \
		res/images/main_timenum_02.png \
		res/images/admin_numbtn07_u.png \
		res/images/main_tapbtn05_select.png \
		res/images/admin_tipsetting_d.png \
		res/images/select_btn02_d.png \
		res/images/admin_numbtn10_u.png \
		res/images/main_tip_timenum_blue02.png \
		res/images/admin_modebtn04_d.png \
		res/images/main_timenum_00.png \
		res/images/admin_numbtn07_d.png \
		res/images/admin_numbtn10_d.png \
		res/images/main_tip_timenum_blue00.png \
		res/images/admin_modebtn06_u.png \
		res/images/logo_bi02.png \
		res/images/admin_bg01.png \
		res/images/admin_bg03.png \
		res/images/admin_numbtn03_u.png \
		res/images/main_tip_timenum_red09.png \
		res/images/main_levelnum_04.png \
		res/images/admin_bg04.png \
		res/images/admin_modebtn06_d.png \
		res/images/main_tapbtn01_unselect.png \
		res/images/admin_numbtn03_d.png \
		res/images/admin_modebtn03_u.png \
		res/images/main_levelnum_02.png \
		res/images/main_tip_timenum_red07.png \
		res/images/main_backbtn_u.png \
		res/images/main_tapbtn02_select.png \
		res/images/main_levelbar_04.png \
		res/images/main_timenum_09.png \
		res/images/admin_modebtn03_d.png \
		res/images/main_backbtn_d.png \
		res/images/admin_numbtn06_u.png \
		res/images/main_tip_timenum_red05.png \
		res/images/main_levelnum_00.png \
		res/images/main_tapbtn04_unselect.png \
		res/images/admin_backbtn_u.png \
		res/images/main_levelbar_02.png \
		res/images/main_tip_timenum_blue09.png \
		res/images/main_timenum_07.png \
		res/images/main_tip_timenum_bg01.png
	/opt/qtrpi/raspi/qt5/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_useriface.cpp moc_sender.cpp moc_receiver.cpp moc_swupdater.cpp moc_logger.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_useriface.cpp moc_sender.cpp moc_receiver.cpp moc_swupdater.cpp moc_logger.cpp
moc_useriface.cpp: include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo \
		include/sender.h \
		include/receiver.h \
		include/swupdater.h \
		include/logger.h \
		include/useriface.h
	/opt/qtrpi/raspi/qt5/bin/moc $(DEFINES) -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++ -I/home/sjpark/hironic/prebuilt5-6/plasonic-application -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -I/home/sjpark/hironic/prebuilt5-6/plasonic-application/include -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtSerialPort -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/opt/qtrpi/raspbian/sysroot/usr/include -I/opt/qtrpi/raspbian/sysroot/usr/include/arm-linux-gnueabihf include/useriface.h -o moc_useriface.cpp

moc_sender.cpp: include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo \
		include/sender.h
	/opt/qtrpi/raspi/qt5/bin/moc $(DEFINES) -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++ -I/home/sjpark/hironic/prebuilt5-6/plasonic-application -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -I/home/sjpark/hironic/prebuilt5-6/plasonic-application/include -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtSerialPort -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/opt/qtrpi/raspbian/sysroot/usr/include -I/opt/qtrpi/raspbian/sysroot/usr/include/arm-linux-gnueabihf include/sender.h -o moc_sender.cpp

moc_receiver.cpp: include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo \
		include/receiver.h
	/opt/qtrpi/raspi/qt5/bin/moc $(DEFINES) -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++ -I/home/sjpark/hironic/prebuilt5-6/plasonic-application -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -I/home/sjpark/hironic/prebuilt5-6/plasonic-application/include -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtSerialPort -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/opt/qtrpi/raspbian/sysroot/usr/include -I/opt/qtrpi/raspbian/sysroot/usr/include/arm-linux-gnueabihf include/receiver.h -o moc_receiver.cpp

moc_swupdater.cpp: include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo \
		include/swupdater.h
	/opt/qtrpi/raspi/qt5/bin/moc $(DEFINES) -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++ -I/home/sjpark/hironic/prebuilt5-6/plasonic-application -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -I/home/sjpark/hironic/prebuilt5-6/plasonic-application/include -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtSerialPort -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/opt/qtrpi/raspbian/sysroot/usr/include -I/opt/qtrpi/raspbian/sysroot/usr/include/arm-linux-gnueabihf include/swupdater.h -o moc_swupdater.cpp

moc_logger.cpp: include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo \
		include/logger.h
	/opt/qtrpi/raspi/qt5/bin/moc $(DEFINES) -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++ -I/home/sjpark/hironic/prebuilt5-6/plasonic-application -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -I/home/sjpark/hironic/prebuilt5-6/plasonic-application/include -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtSerialPort -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/opt/qtrpi/raspbian/sysroot/usr/include -I/opt/qtrpi/raspbian/sysroot/usr/include/arm-linux-gnueabihf include/logger.h -o moc_logger.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp include/useriface.h \
		include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo \
		include/sender.h \
		include/receiver.h \
		include/swupdater.h \
		include/logger.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/QGuiApplication \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qguiapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qeventloop.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qwindowdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qinputmethod.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsize.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/QQmlApplicationEngine \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlapplicationengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qurl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qurlquery.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qjsengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qjsvalue.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qtqmlglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlerror.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmldebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/QQmlEngine \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/QQmlContext \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlcontext.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQuick/QQuickView \
		/opt/qtrpi/raspi/qt5pi/include/QtQuick/qquickview.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQuick/qquickwindow.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQuick/qtquickglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qopengl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qt_windows.h \
		/opt/qtrpi/raspbian/sysroot/opt/vc/include/GLES2/gl2.h \
		/opt/qtrpi/raspbian/sysroot/opt/vc/include/GLES2/gl2platform.h \
		/opt/qtrpi/raspbian/sysroot/opt/vc/include/KHR/khrplatform.h \
		/opt/qtrpi/raspbian/sysroot/opt/vc/include/vcinclude/common.h \
		/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/vcos_stdint.h \
		/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vctypes/vc_image_types.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qopengles2ext.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qopenglext.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qwindow.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QEvent \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMargins \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmargins.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QRect \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrect.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qsurface.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qsurfaceformat.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qicon.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpixmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpaintdevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qcolor.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qrgb.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qrgba64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qimage.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpixelformat.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qtransform.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qmatrix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpolygon.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qregion.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qline.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpainterpath.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qcursor.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qkeysequence.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qvector2d.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qtouchdevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqml.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlprivate.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlparserstatus.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlpropertyvaluesource.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmllist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetaobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

useriface.o: src/useriface.cpp include/useriface.h \
		include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo \
		include/sender.h \
		include/receiver.h \
		include/swupdater.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o useriface.o src/useriface.cpp

sender.o: src/sender.cpp include/sender.h \
		include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sender.o src/sender.cpp

receiver.o: src/receiver.cpp include/receiver.h \
		include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o receiver.o src/receiver.cpp

swupdater.o: src/swupdater.cpp include/swupdater.h \
		include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o swupdater.o src/swupdater.cpp

logger.o: src/logger.cpp include/logger.h \
		include/common.h \
		include/hspsprotocol.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QObject \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_x86.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_unix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QThread \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qthread.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/QSerialPort \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialport.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QString \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDataStream \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDebug \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QtEndian \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qendian.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QMutex \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileSystemWatcher \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfilesystemwatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDir \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdir.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfileinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QDirIterator \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdiriterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QCryptographicHash \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcryptographichash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QFileInfo
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o src/logger.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_useriface.o: moc_useriface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_useriface.o moc_useriface.cpp

moc_sender.o: moc_sender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sender.o moc_sender.cpp

moc_receiver.o: moc_receiver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_receiver.o moc_receiver.cpp

moc_swupdater.o: moc_swupdater.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_swupdater.o moc_swupdater.cpp

moc_logger.o: moc_logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logger.o moc_logger.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/plasonic/bin || mkdir -p $(INSTALL_ROOT)/opt/plasonic/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/plasonic/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/plasonic/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/plasonic/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/plasonic/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

